// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy7IOhPJHaB7vd57k4g9m5UNQmjCR2Kdg',
    appId: '1:611538029065:web:19c2174401e7691edb86d8',
    messagingSenderId: '611538029065',
    projectId: 'pfe2-de743',
    authDomain: 'pfe2-de743.firebaseapp.com',
    databaseURL: 'https://pfe2-de743-default-rtdb.firebaseio.com',
    storageBucket: 'pfe2-de743.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGdaxXDRz63zbCDaIHeOPi1YKoFxoOgi0',
    appId: '1:611538029065:android:255088bb56ce9ec8db86d8',
    messagingSenderId: '611538029065',
    projectId: 'pfe2-de743',
    databaseURL: 'https://pfe2-de743-default-rtdb.firebaseio.com',
    storageBucket: 'pfe2-de743.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxJRbmwn-hH1ur1BI3LlFaigSq2mOwTcY',
    appId: '1:611538029065:ios:e50e2b9d48159eabdb86d8',
    messagingSenderId: '611538029065',
    projectId: 'pfe2-de743',
    databaseURL: 'https://pfe2-de743-default-rtdb.firebaseio.com',
    storageBucket: 'pfe2-de743.appspot.com',
    iosBundleId: 'com.example.picket',
  );
}
